name: Simulate Web Activity

on:
  schedule:
    - cron: '*/1 * * * *'  # Exécute chaque minute
  workflow_dispatch: # Permet de déclencher manuellement

jobs:
  simulate_activity:
    runs-on: ubuntu-latest
    steps:
    - name: Send request to website
      run: curl -X GET https://replit.com/@AmauryBernier/Slycraft-bot-1
